"""API routers for app-main."""

from app_main.api.routers import (
    auth,
    chat,
    commands,
    config,
    context,
    embedding,
    embedding_rebuild,
    episode_profiles,
    insights,
    models,
    notebooks,
    notes,
    podcasts,
    search,
    settings,
    source_chat,
    sources,
    speaker_profiles,
    transformations,
)

__all__ = [
    "auth",
    "chat",
    "commands",
    "config",
    "context",
    "embedding",
    "embedding_rebuild",
    "episode_profiles",
    "insights",
    "models",
    "notebooks",
    "notes",
    "podcasts",
    "search",
    "settings",
    "source_chat",
    "sources",
    "speaker_profiles",
    "transformations",
]
